[package]
name = "qubit-executor"
version = "0.7.1"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-executor"
description = "Executor abstractions, task handles, and basic executor implementations for Qubit Rust libraries"
homepage = "https://github.com/qubit-ltd/rs-executor"
documentation = "https://docs.rs/qubit-executor"
readme = "README.md"
keywords = ["executor", "task", "concurrency", "service"]
categories = ["concurrency", "asynchronous"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/RUST_CODING_STYLE.md",
    "/RUST_CODING_STYLE.zh_CN.md",
    "/doc/**/user_guide*.md",
    "/examples/**",
    "/resources/**",
    "/src/**",
    "/tests/**",
]

[lib]
name = "qubit_executor"
doctest = true

[dependencies]
log = "0.4"
oneshot = { version = "0.2", features = ["async", "std"] }
parking_lot = "0.12"
thiserror = "2.0"

qubit-atomic = "0.13"
qubit-function = { version = "0.16.0", path = "../rs-function" }
qubit-lock = { default-features = false, version = "0.10.0", path = "../rs-lock" }
qubit-cas = { version = "0.9", path = "../rs-cas" }
qubit-state-machine = "0.6"

[dev-dependencies]
tokio = { version = "1.52", features = ["macros", "rt-multi-thread", "time"] }
