[package]
name = "qubit-executor"
version = "0.3.4"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-executor"
description = "Executor abstractions, task handles, and basic executor implementations for Qubit Rust libraries"
homepage = "https://github.com/qubit-ltd/rs-executor"
documentation = "https://docs.rs/qubit-executor"
readme = "README.md"
keywords = ["executor", "task", "concurrency", "service"]
categories = ["concurrency", "asynchronous"]
exclude = [
    "align-ci.sh",
    "ci-check.sh",
    "coverage.sh",
    "style-check.sh",
    "update-submodule.sh",
    ".github/*",
    ".llvm-cov.toml",
    ".cargo-audit.toml.example",
]

[lib]
name = "qubit_executor"
doctest = true

[dependencies]
log = "0.4"
oneshot = { version = "0.2", features = ["async", "std"] }
parking_lot = "0.12"
thiserror = "2.0"

qubit-atomic = "0.11"
qubit-function = "0.13"
qubit-lock = { path = "../rs-lock", default-features = false }
qubit-cas = "0.6"
qubit-state-machine = "0.3"

[dev-dependencies]
tokio = { version = "1.52", features = ["macros", "rt-multi-thread", "time"] }
